// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PucInspectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CertificatePrint")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EngineWarmUp")
                        .HasColumnType("boolean");

                    b.Property<string>("FuelType")
                        .HasColumnType("text");

                    b.Property<bool>("HighRPM")
                        .HasColumnType("boolean");

                    b.Property<bool>("IdleRPM")
                        .HasColumnType("boolean");

                    b.Property<bool>("NormalPUC")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("PucInspectionRecords");
                });

            modelBuilder.Entity("backend.Models.Designation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("backend.Models.Operations.AlignmentChecklistRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BeforeAfterReportPrinted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SteeringCentered")
                        .HasColumnType("boolean");

                    b.Property<bool>("SuspensionChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("TechnicianNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("AlignmentChecklistRecords");
                });

            modelBuilder.Entity("backend.Models.Operations.AlignmentInspectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Complaint")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("InflationPressure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("AlignmentInspectionRecords");
                });

            modelBuilder.Entity("backend.Models.Operations.BalancingChecklistRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FinalRecheckDone")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnicianNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WeightsFixedSecurely")
                        .HasColumnType("boolean");

                    b.Property<bool>("WheelCleaned")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("BalancingChecklistRecords");
                });

            modelBuilder.Entity("backend.Models.Operations.BalancingInspectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Complaint")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("FrontLeftWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FrontRightWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("RearLeftWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RearRightWeight")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("BalancingInspectionRecords");
                });

            modelBuilder.Entity("backend.Models.Operations.BatteryInspectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Complaint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Condition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<double>("SpecificGravity")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<double>("Voltage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("BatteryInspectionRecords");
                });

            modelBuilder.Entity("backend.Models.Operations.CarWashChecklistRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ExteriorWashed")
                        .HasColumnType("boolean");

                    b.Property<bool>("InteriorVacuumed")
                        .HasColumnType("boolean");

                    b.Property<bool>("NoWaterOnEngineElectrics")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnicianNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("CarWashChecklistRecords");
                });

            modelBuilder.Entity("backend.Models.Operations.CarWashInspectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Complaint")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string[]>("SelectedServices")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("CarWashInspectionRecords");
                });

            modelBuilder.Entity("backend.Models.Operations.OilInspectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Complaint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("Quality")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("OilInspectionRecords");
                });

            modelBuilder.Entity("backend.Models.Operations.PucChecklistRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CertificatePrintedAndUploaded")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EngineWarmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProbeInsertedCorrectly")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnicianNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("PucChecklistRecords");
                });

            modelBuilder.Entity("backend.Models.Operations.ServiceEnquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComplaintNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("text");

                    b.Property<string>("CustomerCity")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Odometer")
                        .HasColumnType("integer");

                    b.Property<string>("PinCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Wheel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("VehicleNo");

                    b.ToTable("ServiceEnquiries");
                });

            modelBuilder.Entity("backend.Models.Operations.ServiceEnquiryService", b =>
                {
                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ActualMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("PriceCharged")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServiceEnquiryId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceEnquiryServices");
                });

            modelBuilder.Entity("backend.Models.Operations.TyreChecklistRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CorrectInflation")
                        .HasColumnType("boolean");

                    b.Property<bool>("CorrectTyreSizeVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("NoBeadSidewallDamage")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnicianNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WheelNutsTorqued")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("TyreChecklistRecords");
                });

            modelBuilder.Entity("backend.Models.Operations.TyreInspectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomComplaint")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RotationComplaint")
                        .HasColumnType("text");

                    b.Property<string>("RotationType")
                        .HasColumnType("text");

                    b.Property<string[]>("SelectedComplaints")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("SelectedTyre")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("TyreInspectionRecords");
                });

            modelBuilder.Entity("backend.Models.Operations.TyreRotationInspectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Complaint")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RotationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceEnquiryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ServiceEnquiryId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("TyreRotationInspectionRecords");
                });

            modelBuilder.Entity("backend.Models.ServiceManagement.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("backend.Models.UserDesignation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DesignationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedById")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "DesignationId");

                    b.HasIndex("AssignedById");

                    b.HasIndex("DesignationId");

                    b.ToTable("UserDesignations");
                });

            modelBuilder.Entity("backend.Models.auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PucInspectionRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("PucInspection")
                        .HasForeignKey("PucInspectionRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Designation", b =>
                {
                    b.HasOne("backend.Models.ServiceManagement.Service", "Service")
                        .WithOne("Designation")
                        .HasForeignKey("backend.Models.Designation", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Service");
                });

            modelBuilder.Entity("backend.Models.Operations.AlignmentChecklistRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("AlignmentChecklist")
                        .HasForeignKey("backend.Models.Operations.AlignmentChecklistRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Operations.AlignmentInspectionRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("AlignmentInspection")
                        .HasForeignKey("backend.Models.Operations.AlignmentInspectionRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Operations.BalancingChecklistRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("BalancingChecklist")
                        .HasForeignKey("backend.Models.Operations.BalancingChecklistRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Operations.BalancingInspectionRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("BalancingInspection")
                        .HasForeignKey("backend.Models.Operations.BalancingInspectionRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Operations.BatteryInspectionRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("BatteryInspection")
                        .HasForeignKey("backend.Models.Operations.BatteryInspectionRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Operations.CarWashChecklistRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("CarWashChecklist")
                        .HasForeignKey("backend.Models.Operations.CarWashChecklistRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Operations.CarWashInspectionRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("CarWashInspection")
                        .HasForeignKey("backend.Models.Operations.CarWashInspectionRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Operations.OilInspectionRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("OilInspection")
                        .HasForeignKey("backend.Models.Operations.OilInspectionRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Operations.PucChecklistRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("PucChecklist")
                        .HasForeignKey("backend.Models.Operations.PucChecklistRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Operations.ServiceEnquiry", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Operations.ServiceEnquiryService", b =>
                {
                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithMany("SelectedServices")
                        .HasForeignKey("ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.ServiceManagement.Service", "Service")
                        .WithMany("EnquiryServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("ServiceEnquiry");
                });

            modelBuilder.Entity("backend.Models.Operations.TyreChecklistRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("TyreChecklist")
                        .HasForeignKey("backend.Models.Operations.TyreChecklistRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Operations.TyreInspectionRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("TyreInspection")
                        .HasForeignKey("backend.Models.Operations.TyreInspectionRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.OwnsOne("backend.Models.Operations.TyreValues", "FrontLeft", b1 =>
                        {
                            b1.Property<Guid>("TyreInspectionRecordId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TreadDepth")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FrontLeft_TreadDepth");

                            b1.Property<int>("TyrePressure")
                                .HasColumnType("integer")
                                .HasColumnName("FrontLeft_TyrePressure");

                            b1.HasKey("TyreInspectionRecordId");

                            b1.ToTable("TyreInspectionRecords");

                            b1.WithOwner()
                                .HasForeignKey("TyreInspectionRecordId");
                        });

                    b.OwnsOne("backend.Models.Operations.TyreValues", "FrontRight", b1 =>
                        {
                            b1.Property<Guid>("TyreInspectionRecordId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TreadDepth")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FrontRight_TreadDepth");

                            b1.Property<int>("TyrePressure")
                                .HasColumnType("integer")
                                .HasColumnName("FrontRight_TyrePressure");

                            b1.HasKey("TyreInspectionRecordId");

                            b1.ToTable("TyreInspectionRecords");

                            b1.WithOwner()
                                .HasForeignKey("TyreInspectionRecordId");
                        });

                    b.OwnsOne("backend.Models.Operations.TyreValues", "RearLeft", b1 =>
                        {
                            b1.Property<Guid>("TyreInspectionRecordId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TreadDepth")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("RearLeft_TreadDepth");

                            b1.Property<int>("TyrePressure")
                                .HasColumnType("integer")
                                .HasColumnName("RearLeft_TyrePressure");

                            b1.HasKey("TyreInspectionRecordId");

                            b1.ToTable("TyreInspectionRecords");

                            b1.WithOwner()
                                .HasForeignKey("TyreInspectionRecordId");
                        });

                    b.OwnsOne("backend.Models.Operations.TyreValues", "RearRight", b1 =>
                        {
                            b1.Property<Guid>("TyreInspectionRecordId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TreadDepth")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("RearRight_TreadDepth");

                            b1.Property<int>("TyrePressure")
                                .HasColumnType("integer")
                                .HasColumnName("RearRight_TyrePressure");

                            b1.HasKey("TyreInspectionRecordId");

                            b1.ToTable("TyreInspectionRecords");

                            b1.WithOwner()
                                .HasForeignKey("TyreInspectionRecordId");
                        });

                    b.Navigation("CreatedByUser");

                    b.Navigation("FrontLeft");

                    b.Navigation("FrontRight");

                    b.Navigation("RearLeft");

                    b.Navigation("RearRight");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.Operations.TyreRotationInspectionRecord", b =>
                {
                    b.HasOne("backend.Models.auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("backend.Models.Operations.ServiceEnquiry", "ServiceEnquiry")
                        .WithOne("TyreRotationInspection")
                        .HasForeignKey("backend.Models.Operations.TyreRotationInspectionRecord", "ServiceEnquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ServiceEnquiry");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("backend.Models.UserDesignation", b =>
                {
                    b.HasOne("backend.Models.auth.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById");

                    b.HasOne("backend.Models.Designation", "Designation")
                        .WithMany("UserDesignations")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.auth.User", "User")
                        .WithMany("UserDesignations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("Designation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Designation", b =>
                {
                    b.Navigation("UserDesignations");
                });

            modelBuilder.Entity("backend.Models.Operations.ServiceEnquiry", b =>
                {
                    b.Navigation("AlignmentChecklist");

                    b.Navigation("AlignmentInspection");

                    b.Navigation("BalancingChecklist");

                    b.Navigation("BalancingInspection");

                    b.Navigation("BatteryInspection");

                    b.Navigation("CarWashChecklist");

                    b.Navigation("CarWashInspection");

                    b.Navigation("OilInspection");

                    b.Navigation("PucChecklist");

                    b.Navigation("PucInspection");

                    b.Navigation("SelectedServices");

                    b.Navigation("TyreChecklist");

                    b.Navigation("TyreInspection");

                    b.Navigation("TyreRotationInspection");
                });

            modelBuilder.Entity("backend.Models.ServiceManagement.Service", b =>
                {
                    b.Navigation("Designation");

                    b.Navigation("EnquiryServices");
                });

            modelBuilder.Entity("backend.Models.auth.User", b =>
                {
                    b.Navigation("UserDesignations");
                });
#pragma warning restore 612, 618
        }
    }
}
